const { json } = require("express");
const express = require("express");
const cors = require("cors");
const PORT = process.env.PORT || 5000;
const productsRoute = require("./Routes/products-route");
const ordersRoute = require("./Routes/orders-route");
const customersRoute = require("./Routes/customers-route");
const cartRoute = require("./Routes/cart-route");
const app = express();
app.use(json());
app.use(cors({ origin: "*" }));
app.use(productsRoute);
app.use(ordersRoute);
app.use(customersRoute);
app.use(cartRoute);
app.listen(PORT, () => console.log(`listening on port ${PORT}`));
